builders:
  easyLocalizationKeysGenerator:
    import: "package:easy_localization_keys_generator/easy_localization_keys_generator.dart"
    builder_factories: ["easyLocalizationKeysGenerator"]
    build_extensions: {
      '^assets/{{}}.json': ['assets/generated/{{}}.dart'],
      '^assets/{{}}.yaml': ['assets/generated/{{}}.dart'],
    }
    build_to: source
    auto_apply: root_package